version: '3.8'

services:
  chat-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-bot
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.json:/app/config/config.json
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
