version: '3.8'

services:
  chat-bot:
    image: vibin/chat-bot:latest
    container_name: chat-bot
    ports:
      - "8099:8080"
    volumes:
      - ./config/config.json:/app/config/config.json
      - /root/chatbot-data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
